@startuml
'https://plantuml.com/sequence-diagram

autonumber
participant "运营" as User #green
participant "Dash" as Dash #skyblue
participant "Merchant" as Merchant #skyblue
User -> Dash: 进入店铺管理页面
Dash -> Dash: 查询店铺列表（带店铺状态）
Dash --> User: 店铺列表
User -> Dash: 冻结店铺（storeId，freezeType）
Dash -> Dash: 是否支持此冻结类型
Dash -> Dash: 店铺是否已是此冻结类型
Dash -> Dash: 拼接冻结操作的desc
Dash -> Merchant: 调用Dubbo接口更新店铺状态
Merchant --> Dash: 更新成功
Dash --> User: 冻结成功
@enduml