@startuml
'https://plantuml.com/sequence-diagram

autonumber

前端 -> shoplytics: 查询首页地图汇总数据
shoplytics -> shoplytics: 根据店铺时区对时间戳进行处理
shoplytics -> 数据中台: apiSeq：SL_SellerAdminShoplytics_realtimeanAlytics_homepage_summary（查询pv等数据）
数据中台 --> shoplytics: 返回结果
shoplytics -> 数据中台: apiSeq：SL_SellerAdminShoplytics_realtimeanAlytics_comsumer_action（单独查询uv）
数据中台 --> shoplytics: 返回结果
shoplytics ->shoplytics: 组装数据
shoplytics --> 前端: 返回最终结果

@enduml

