@startuml
'https://plantuml.com/sequence-diagram

autonumber
participant "Google" as Google #green
participant "建站" as Station #green
participant "Merchant" as Merchant #skyblue
participant "S3" as S3 #skyblue
participant "Product" as Product #skyblue
participant "MySQL" as MySQL #skyblue
participant "Redis" as Redis #skyblue
Google -> Station: 访问siteMap链接 domain+"/sitemap.xml"
Station -> Merchant: 调用接口（/api/merchant/store/sitemap/station,header带上domain和path,cookie带上storeId）
Merchant -> Merchant: 根据domain查找storeId，校验domain的合法性
Merchant -> MySQL: 根据storeId、domain、path查询sitemap.xml的上传记录
MySQL --> Merchant: 返回查询结果
alt null != siteMapRecord
Merchant -> S3: 根据 key 下载文件
note right: 查询不做过期时间判断，统一由定时任务完成定时刷新
S3 --> Merchant: 返回文件内容
Merchant --> Station: 返回xml内容
Station --> Google: 返回xml内容
else null == siteMapRecord
Merchant -> Redis: 利用 Redisson 获取分布式锁
note right: key 的粒度细到店铺的每个domain\nkey: sitemap:main:storeId:domain:path、waitTime：10s、leaseTime：60*10s
alt tryLock -> true
Merchant -> MySQL: 根据storeId、domain、path查询sitemap.xml的上传记录
note right: 二次检查，防止等待的线程在等待超时前拿到了锁，继续生成新的文件新的记录
MySQL --> Merchant: 返回查询结果
alt null == siteMapRecord
Merchant --> Merchant: 异步生成 sitemap_pages_1.xml
loop 轮询5次，最多支持25w商品
note right: pageNum: 1、501、1001、1501、2001；pageSize：100
Merchant -> Product: 分页查询商品列表
Product --> Merchant: 查询结果：hasNext、productList
note right: 如果hasNext为false，跳出循环
alt 查询成功&商品列表不为空
Merchant -> Product: pageNum = pageNum+5、pageSize=100
note right: 判断当前索引是否大于500条
Product --> Merchant: 返回结果
Merchant -> Merchant: productList不为空，异步生成 sitemap_products_{index}.xml.gz,否则生成 sitemap_products_{index}.xml
else
Merchant -> Merchant: 下一轮
end
end
Merchant -> Product: 查询分类、pageNum=6，pageSize=100
Product -> Merchant: 返回结果
Merchant -> Merchant: collectionList不为空，异步生成 sitemap_collections_{index}.xml.gz,否则生成 sitemap_collections_{index}.xml
else null != siteMapRecord
Merchant -> S3: 根据 key 下载文件
S3 --> Merchant: 返回文件内容
end
Merchant --> Station: 返回xml内容
Station --> Google: 返回xml内容
Merchant -> Redis: 释放锁
else tryLock -> false
Merchant --> 接入层: 返回空
接入层 --> Google: 返回空
end
end
@enduml