@startuml
'https://plantuml.com/sequence-diagram

autonumber
participant "ec-*" as Service #green
participant "资源服务" as Resource #skyblue
participant "Pulsar" as Pulsar #skyblue
participant "S3Client" as S3 #skyblue
participant "OssClient" as OSS #skyblue

Service -> Resource: ResourceApi#batchUploadImageByUrlAsyn（文件url、最大文件大小...）
activate Resource #FFBBBB
loop 批量的数量，利用线程池异步并发进行
group 根据url下载图片
Resource -> Resource: 获取最大文件大小配置，如果传参为空则读配置文件
Resource -> Resource: 利用OkClient获取文件输入流
Resource -> Resource: 获取图片二进制数组
end
Resource -> Resource: 获取图片类型
Resource -> Resource: 检查类型
Resource -> Resource: 生成ImageStorageKey（S3和OSS公用）
Resource -> Resource: 根据key和cdnDomain拼接url
Resource -> Resource: 返回组装信息（originalUrl&newUrl）
Resource -> Pulsar: 发送mq信息，异步上传图片（ImageStorageKey、imageUrl...）
end
loop 批量的数量
Resource -> Resource: 同步等待获取结果
end
Resource --> Service: 返回结果列表
deactivate Resource #FFBBBB
@enduml