@startuml
'https://plantuml.com/sequence-diagram

autonumber
participant "ec-*" as Service #green
participant "资源服务" as Resource #skyblue
participant "S3Client" as S3 #skyblue
Service -> Resource: ResourceApi#downloadFile（文件key）
activate Resource #FFBBBB
Resource -> S3: 根据Key获取文件（getPrivateObject）
S3 --> Resource: 返回文件二进制数据
Resource -> Resource: 根据文件Key获取文件名称
Resource --> Service: 返回文件二进制数据&名称
deactivate Resource #FFBBBB
@enduml