@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant "Front" as Front #green
participant "Dash" as Dash #skyblue
participant "Merchant" as Merchant #skyblue
participant "Redis" as Redis #skyblue

Front-> Dash:导入文件（支持xls、xlsx和csv）
Dash -> Redis: 上锁
alt 成功
Dash -> Dash: 文件大小校验、文件类型校验
loop 读取文件内容（一行一行读取）
Dash -> Dash: 判断输入内容，没问题的放入successList，有错误的放入failList
end
Dash -> Dash: 判断successList是否为空
alt CollectionUtils.isNotEmpty(successList)
Dash -> Merchant: 调用Dubbo接口批量插入
Merchant -> Dash: 返回结果
Dash -> Dash: 记录成功数
end
Dash -> Dash: 记录失败数
Dash -> Dash: 封装导入结果
Dash -> Front: 返回导入结果
else 失败
Dash -> Front: 直接返回：已有账号在导入
end
@enduml